name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
      GitHubPackageFeedUrl: https://nuget.pkg.github.com/GitHubDevOps-Team3/index.json
      LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
      AZURE_WEBAPP_NAME: animal-adoption-portal  # set this to your application's name
      VERSION: 1.0.0
      AZURE_WEBAPP_PACKAGE_PATH: '.'  # set this to the path to your web app project, defaults to the repository root
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

# Authenticates packages to push to GPR
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
    - name: Package up project
      run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}

    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
    - name: Publish web portal
      run: dotnet publish AnimalAdoption.Web.Portal -o AnimalAdoption.Web.Portal/published
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ github.workspace }}/AnimalAdoption.Web.Portal/published

